CREATE TABLE personality (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personality_key varchar(64) NOT NULL,
    display_name varchar(80) NOT NULL,
    description varchar(280) NOT NULL,
    prompt_traits text NOT NULL,
    speaking_probability numeric(4, 3) NOT NULL,
    style_guidance text NOT NULL,
    boundary_guidance text NOT NULL,
    avatar_ref varchar(255),
    display_order integer NOT NULL,
    is_system boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT personality_pkey PRIMARY KEY (id),
    CONSTRAINT personality_key_unique UNIQUE (personality_key),
    CONSTRAINT personality_speaking_probability_check
        CHECK (speaking_probability >= 0.000 AND speaking_probability <= 1.000),
    CONSTRAINT personality_display_order_check CHECK (display_order >= 0)
);

CREATE INDEX personality_selectable_order_idx
    ON personality (display_order, personality_key)
    WHERE is_system = true AND is_active = true;
