CREATE TABLE dialogue_line (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id uuid NOT NULL,
    trigger_type varchar(32) NOT NULL,
    trigger_ply integer NOT NULL,
    personality_key varchar(64) NOT NULL,
    personality_display_name varchar(80) NOT NULL,
    dialogue_text varchar(280) NOT NULL,
    emotion varchar(32) NOT NULL,
    reaction_type varchar(32) NOT NULL,
    response_source varchar(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT dialogue_line_pkey PRIMARY KEY (id),
    CONSTRAINT dialogue_line_personality_fk
        FOREIGN KEY (personality_key) REFERENCES personality(personality_key),
    CONSTRAINT dialogue_line_trigger_ply_check CHECK (trigger_ply >= 0),
    CONSTRAINT dialogue_line_unique_trigger_speaker
        UNIQUE (match_id, trigger_type, trigger_ply, personality_key)
);

CREATE INDEX dialogue_line_match_history_idx
    ON dialogue_line (match_id, id);
